export const defaultDocumentList = [
  "BOB (Breakdown of benefits)",
  "Insurance Fax Back",
  "Treatment consent",
  "N2O Consent",
  "Signed Treatment Plan",
  "Pre-D",
  "Driver License",
  "Spouse Driver License",
  "Ins Card",
  "Ortho Rx",
  "Lab Certificate",
  "DFA",
  "Smile Mock Up",
  "Implant Info",
  "Lab Rx",
  "Lab Invoice",
  "Financial Agreement",
  "Confidential Info",
  "Medical/Dental History",
  "Referral form",
  "XRAY",
  "Demographics",
  "Invisalign",
  "Dental History",
  "BOB (Breakdown of benefits) - Sec",
  "BOB (Breakdown of benefits) - Pri",
  "Insurance Fax Back - Pri",
  "Insurance Fax Back - Sec"
];

export const defaultCategoryList = [
  "Insurance",
  "Consent",
  "Medical/Dental History",
  "Treatment Plan",
  "Referral",
  "Signed Receipt",
  "Medications",
  "ID",
  "Lab",
  "Injectables",
  "Consult",
  "Ortho",
  "Implant certificate",
  "Evident Hub",
  "New Patient Forms",
  "XRAY",
  "Demographics",
  "Eligibility verified (Detailed)",
  "Diagnosis",
  "Invisalign",
  "New Patient",
  "Eligibility verification",
  "Outstanding Balance"
];
