export const TIME_ZONES = [
  { value: 'UTC', label: 'UTC (Coordinated Universal Time)' },
  { value: 'America/New_York', label: 'America/New_York (Eastern Time)' },
  { value: 'America/Chicago', label: 'America/Chicago (Central Time)' },
  { value: 'America/Denver', label: 'America/Denver (Mountain Time)' },
  { value: 'America/Los_Angeles', label: 'America/Los_Angeles (Pacific Time)' },
  { value: 'America/Phoenix', label: 'America/Phoenix (Mountain Time - No DST)' },
  { value: 'America/Anchorage', label: 'America/Anchorage (Alaska Time)' },
  { value: 'America/Honolulu', label: 'America/Honolulu (Hawaii Time)' },
  { value: 'America/Toronto', label: 'America/Toronto (Eastern Time)' },
  { value: 'America/Vancouver', label: 'America/Vancouver (Pacific Time)' },
  { value: 'America/Montreal', label: 'America/Montreal (Eastern Time)' },
  { value: 'America/Winnipeg', label: 'America/Winnipeg (Central Time)' },
  { value: 'America/Calgary', label: 'America/Calgary (Mountain Time)' },
  { value: 'America/Halifax', label: 'America/Halifax (Atlantic Time)' },
  { value: 'America/Mexico_City', label: 'America/Mexico_City (Central Time)' },
  { value: 'America/Bogota', label: 'America/Bogota (Colombia Time)' },
  { value: 'America/Lima', label: 'America/Lima (Peru Time)' },
  { value: 'America/Santiago', label: 'America/Santiago (Chile Time)' },
  { value: 'America/Sao_Paulo', label: 'America/Sao_Paulo (Brasilia Time)' },
  { value: 'America/Buenos_Aires', label: 'America/Buenos_Aires (Argentina Time)' },
  { value: 'America/Caracas', label: 'America/Caracas (Venezuela Time)' },
  { value: 'America/La_Paz', label: 'America/La_Paz (Bolivia Time)' },
  { value: 'Europe/London', label: 'Europe/London (Greenwich Mean Time)' },
  { value: 'Europe/Paris', label: 'Europe/Paris (Central European Time)' },
  { value: 'Europe/Berlin', label: 'Europe/Berlin (Central European Time)' },
  { value: 'Europe/Rome', label: 'Europe/Rome (Central European Time)' },
  { value: 'Europe/Madrid', label: 'Europe/Madrid (Central European Time)' },
  { value: 'Europe/Amsterdam', label: 'Europe/Amsterdam (Central European Time)' },
  { value: 'Europe/Brussels', label: 'Europe/Brussels (Central European Time)' },
  { value: 'Europe/Vienna', label: 'Europe/Vienna (Central European Time)' },
  { value: 'Europe/Zurich', label: 'Europe/Zurich (Central European Time)' },
  { value: 'Europe/Stockholm', label: 'Europe/Stockholm (Central European Time)' },
  { value: 'Europe/Copenhagen', label: 'Europe/Copenhagen (Central European Time)' },
  { value: 'Europe/Oslo', label: 'Europe/Oslo (Central European Time)' },
  { value: 'Europe/Dublin', label: 'Europe/Dublin (Greenwich Mean Time)' },
  { value: 'Europe/Lisbon', label: 'Europe/Lisbon (Western European Time)' },
  { value: 'Europe/Warsaw', label: 'Europe/Warsaw (Central European Time)' },
  { value: 'Europe/Prague', label: 'Europe/Prague (Central European Time)' },
  { value: 'Europe/Budapest', label: 'Europe/Budapest (Central European Time)' },
  { value: 'Europe/Athens', label: 'Europe/Athens (Eastern European Time)' },
  { value: 'Europe/Bucharest', label: 'Europe/Bucharest (Eastern European Time)' },
  { value: 'Europe/Sofia', label: 'Europe/Sofia (Eastern European Time)' },
  { value: 'Europe/Helsinki', label: 'Europe/Helsinki (Eastern European Time)' },
  { value: 'Europe/Moscow', label: 'Europe/Moscow (Moscow Time)' },
  { value: 'Asia/Dubai', label: 'Asia/Dubai (Gulf Standard Time)' },
  { value: 'Asia/Riyadh', label: 'Asia/Riyadh (Arabia Standard Time)' },
  { value: 'Asia/Kuwait', label: 'Asia/Kuwait (Arabia Standard Time)' },
  { value: 'Asia/Qatar', label: 'Asia/Qatar (Arabia Standard Time)' },
  { value: 'Asia/Bahrain', label: 'Asia/Bahrain (Arabia Standard Time)' },
  { value: 'Asia/Muscat', label: 'Asia/Muscat (Gulf Standard Time)' },
  { value: 'Asia/Karachi', label: 'Asia/Karachi (Pakistan Standard Time)' },
  { value: 'Asia/Kolkata', label: 'Asia/Kolkata (India Standard Time)' },
  { value: 'Asia/Dhaka', label: 'Asia/Dhaka (Bangladesh Standard Time)' },
  { value: 'Asia/Colombo', label: 'Asia/Colombo (Sri Lanka Time)' },
  { value: 'Asia/Kathmandu', label: 'Asia/Kathmandu (Nepal Time)' },
  { value: 'Asia/Kabul', label: 'Asia/Kabul (Afghanistan Time)' },
  { value: 'Asia/Tehran', label: 'Asia/Tehran (Iran Standard Time)' },
  { value: 'Asia/Baghdad', label: 'Asia/Baghdad (Arabia Standard Time)' },
  { value: 'Asia/Jerusalem', label: 'Asia/Jerusalem (Israel Standard Time)' },
  { value: 'Asia/Beirut', label: 'Asia/Beirut (Eastern European Time)' },
  { value: 'Asia/Amman', label: 'Asia/Amman (Eastern European Time)' },
  { value: 'Asia/Damascus', label: 'Asia/Damascus (Eastern European Time)' },
  { value: 'Asia/Bangkok', label: 'Asia/Bangkok (Indochina Time)' },
  { value: 'Asia/Singapore', label: 'Asia/Singapore (Singapore Time)' },
  { value: 'Asia/Kuala_Lumpur', label: 'Asia/Kuala_Lumpur (Malaysia Time)' },
  { value: 'Asia/Jakarta', label: 'Asia/Jakarta (Western Indonesia Time)' },
  { value: 'Asia/Manila', label: 'Asia/Manila (Philippine Time)' },
  { value: 'Asia/Hong_Kong', label: 'Asia/Hong_Kong (Hong Kong Time)' },
  { value: 'Asia/Shanghai', label: 'Asia/Shanghai (China Standard Time)' },
  { value: 'Asia/Taipei', label: 'Asia/Taipei (Taiwan Standard Time)' },
  { value: 'Asia/Tokyo', label: 'Asia/Tokyo (Japan Standard Time)' },
  { value: 'Asia/Seoul', label: 'Asia/Seoul (Korea Standard Time)' },
  { value: 'Asia/Almaty', label: 'Asia/Almaty (Kazakhstan Time)' },
  { value: 'Asia/Tashkent', label: 'Asia/Tashkent (Uzbekistan Time)' },
  { value: 'Asia/Baku', label: 'Asia/Baku (Azerbaijan Time)' },
  { value: 'Asia/Yerevan', label: 'Asia/Yerevan (Armenia Time)' },
  { value: 'Asia/Tbilisi', label: 'Asia/Tbilisi (Georgia Time)' },
  { value: 'Africa/Cairo', label: 'Africa/Cairo (Eastern European Time)' },
  { value: 'Africa/Johannesburg', label: 'Africa/Johannesburg (South Africa Standard Time)' },
  { value: 'Africa/Lagos', label: 'Africa/Lagos (West Africa Time)' },
  { value: 'Africa/Nairobi', label: 'Africa/Nairobi (East Africa Time)' },
  { value: 'Australia/Sydney', label: 'Australia/Sydney (Australian Eastern Time)' },
  { value: 'Australia/Melbourne', label: 'Australia/Melbourne (Australian Eastern Time)' },
  { value: 'Australia/Brisbane', label: 'Australia/Brisbane (Australian Eastern Time)' },
  { value: 'Australia/Perth', label: 'Australia/Perth (Australian Western Time)' },
  { value: 'Australia/Adelaide', label: 'Australia/Adelaide (Australian Central Time)' },
  { value: 'Pacific/Auckland', label: 'Pacific/Auckland (New Zealand Time)' },
  { value: 'Pacific/Honolulu', label: 'Pacific/Honolulu (Hawaii Time)' }
];

export const STATE_TIME_ZONES = {
  AL: ['America/Chicago'],
  AK: ['America/Anchorage'],
  AZ: ['America/Phoenix'],
  AR: ['America/Chicago'],
  CA: ['America/Los_Angeles'],
  CO: ['America/Denver'],
  CT: ['America/New_York'],
  DE: ['America/New_York'],
  FL: ['America/New_York'],
  GA: ['America/New_York'],
  HI: ['Pacific/Honolulu'],
  ID: ['America/Denver'],
  IL: ['America/Chicago'],
  IN: ['America/New_York', 'America/Chicago'],
  IA: ['America/Chicago'],
  KS: ['America/Chicago', 'America/Denver'],
  KY: ['America/New_York', 'America/Chicago'],
  LA: ['America/Chicago'],
  ME: ['America/New_York'],
  MD: ['America/New_York'],
  MA: ['America/New_York'],
  MI: ['America/New_York', 'America/Chicago'],
  MN: ['America/Chicago'],
  MS: ['America/Chicago'],
  MO: ['America/Chicago'],
  MT: ['America/Denver'],
  NE: ['America/Chicago', 'America/Denver'],
  NV: ['America/Los_Angeles'],
  NH: ['America/New_York'],
  NJ: ['America/New_York'],
  NM: ['America/Denver'],
  NY: ['America/New_York'],
  NC: ['America/New_York'],
  ND: ['America/Chicago', 'America/Denver'],
  OH: ['America/New_York'],
  OK: ['America/Chicago'],
  OR: ['America/Los_Angeles'],
  PA: ['America/New_York'],
  RI: ['America/New_York'],
  SC: ['America/New_York'],
  SD: ['America/Chicago', 'America/Denver'],
  TN: ['America/Chicago'],
  TX: ['America/Chicago'],
  UT: ['America/Denver'],
  VT: ['America/New_York'],
  VA: ['America/New_York'],
  WA: ['America/Los_Angeles'],
  WV: ['America/New_York'],
  WI: ['America/Chicago'],
  WY: ['America/Denver']
};