// Claim type options
export const CLAIM_TYPES = [
  { value: 'all', label: 'All' },
  { value: 'Manual Primary', label: 'Manual Primary' },
  { value: 'Manual Secondary', label: 'Manual Secondary' },
  { value: 'Manual Other', label: 'Manual Other' },
  { value: 'All E-claim Primary', label: 'All E-claim Primary' },
  { value: 'E-claim Other', label: 'E-claim Other' },
  { value: 'E-claim Secondary', label: 'E-claim Secondary' },
  { value: 'Manual Preauth Primary', label: 'Manual Preauth Primary' },
  { value: 'Manual Preauth Secondary', label: 'Manual Preauth Secondary' },
  { value: 'Manual Preauth Other', label: 'Manual Preauth Other' },
  { value: 'E-preauth Primary', label: 'E-preauth Primary' },
  { value: 'E-preauth Secondary', label: 'E-preauth Secondary' },
  { value: 'E-preauth Other', label: 'E-preauth Other' },
];

// Carrier options
export const CARRIERS = [
  { value: 'all', label: 'All' },
  { value: 'bcbs', label: 'Blue Cross Blue Shield' },
  { value: 'metlife', label: 'Metlife' },
  { value: 'aetna', label: 'Aetna Dental' },
  { value: 'guardian', label: 'Guardian Life' },
  { value: 'cigna', label: 'Cigna Dental' },
  { value: 'delta', label: 'Delta Dental Ins.' },
  { value: 'uhc', label: 'United Healthcare' },
  { value: 'humana', label: 'Humana Dental' },
  { value: 'principal', label: 'Principal Financial' },
  { value: 'anthem', label: 'Anthem' },
  { value: 'geha', label: 'GEHA Connection' },
];

// Claim Status Options (aligned with backend ClaimStatus values)
export const CLAIM_STATUSES = [
  { value: 'all', label: 'All' },
  { value: 'Accepted', label: 'Accepted' },
  { value: 'Accepted and Paid', label: 'Accepted and Paid' },
  { value: 'Accepted for processing', label: 'Accepted for processing' },
  { value: 'Accepted, but a final payment was denied', label: 'Accepted, but a final payment was denied' },
  { value: 'Additional Info Requested', label: 'Additional Info Requested' },
  { value: 'An error occurred when submitting the claim attachments', label: 'An error occurred when submitting the claim attachments' },
  { value: 'COB Submitted', label: 'COB Submitted' },
  { value: 'Claim in process', label: 'Claim in process' },
  { value: 'Contact Oryx Support', label: 'Contact Oryx Support' },
  { value: 'Created', label: 'Created' },
  { value: 'Deleted', label: 'Deleted' },
  { value: 'EOB Received', label: 'EOB Received' },
  { value: 'EOB Uploaded', label: 'EOB Uploaded' },
  { value: 'Edi Validation Error - Contact Oryx Support', label: 'Edi Validation Error - Contact Oryx Support' },
  { value: 'Error Response Received', label: 'Error Response Received' },
  { value: 'Manual Claim', label: 'Manual Claim' },
  { value: 'Payment was Denied', label: 'Payment was Denied' },
  { value: 'Pending At Payor', label: 'Pending At Payor' },
];

// Group Date By Range Options (Specific to Outstanding Claims)
export const DATE_RANGES = [
  { value: 'none', label: 'None' },
  { value: '0_30', label: '0-30 days' },
  { value: '31_60', label: '31-60 days' },
  { value: '61_90', label: '61-90 days' },
  { value: '90_plus', label: '90+ days' },
];

// Group By Options (Specific to Outstanding Claims)
export const GROUP_BY_OPTIONS = [
  { value: 'none', label: 'None' },
  { value: 'carrier', label: 'Carrier' },
  { value: 'patient', label: 'Patient' },
  { value: 'provider', label: 'Provider' },
];

// Complete combined mock data for claims
export const INITIAL_CLAIMS = [
  // 1-9: UNSENT CLAIMS
  {
    id: '1',
    patientName: 'Leticia Carter',
    patientCode: '(#0418)',
    patientDob: '08/12/1988',
    claimNumber: '#25390',
    claimType: 'E-claim Primary',
    createdDate: '05/21/2026',
    carrier: 'Blue Cross Blue Shield of Texas',
    status: 'readyForSubmission',
    notes: 'Prior auth attached, check policy limits',
    description: 'Waiting for the crown to be seated.',
    procedures: [
      { code: 'D2740', name: 'Crown - Porcelain/Ceramic Substrate', fee: 1150.00 },
      { code: 'D0120', name: 'Periodic Oral Evaluation - Established Patient', fee: 55.00 },
    ],
    tab: 'unsent',
  },
  {
    id: '2',
    patientName: 'Russell Rudolf',
    patientCode: '(#0097)',
    patientDob: '10/24/1975',
    claimNumber: '#25401',
    claimType: 'E-claim Primary',
    createdDate: '05/21/2026',
    carrier: 'Metlife',
    status: 'readyForSubmission',
    notes: 'Sent via standard gateway',
    description: 'F/U 06/05/2026 BH. We have submitted the required digital charting. Previous SRP History: 06/01/2024.',
    procedures: [
      { code: 'D4341', name: 'Periodontal Scaling & Root Planing - 4+ Teeth', fee: 280.00 },
      { code: 'D4910', name: 'Periodontal Maintenance', fee: 140.00 },
    ],
    tab: 'unsent',
  },
  {
    id: '3',
    patientName: 'Evan Romero',
    patientCode: '(#0134)',
    patientDob: '05/16/1990',
    claimNumber: '#25407',
    claimType: 'E-claim Primary',
    createdDate: '05/21/2026',
    carrier: 'Aetna Dental',
    status: 'validationError',
    notes: 'Validation Alert: Missing Subscriber ID or invalid group format.',
    description: 'Member is not active on DOS Eff...',
    procedures: [
      { code: 'D2331', name: 'Resin-Based Composite - 2 Surfaces, Anterior', fee: 210.00 },
    ],
    tab: 'unsent',
  },
  {
    id: '4',
    patientName: 'Gabriel Medina',
    patientCode: '(#0011)',
    patientDob: '12/03/1995',
    claimNumber: '#25474',
    claimType: 'E-claim Primary',
    createdDate: '05/21/2026',
    carrier: 'Guardian Life',
    status: 'readyForSubmission',
    notes: 'Discount schedule applied',
    description: 'It is a discounted plan',
    procedures: [
      { code: 'D1110', name: 'Prophylaxis - Adult', fee: 95.00 },
      { code: 'D1208', name: 'Topical Application of Fluoride', fee: 35.00 },
    ],
    tab: 'unsent',
  },
  {
    id: '5',
    patientName: 'Ronald Patterson',
    patientCode: '(#0293)',
    patientDob: '02/14/1982',
    claimNumber: '#25574',
    claimType: 'E-claim Primary',
    createdDate: '05/19/2026',
    carrier: 'Cigna Dental',
    status: 'readyForSubmission',
    notes: 'Awaiting clinical notes',
    description: 'Waiting for the crown to be seated.',
    procedures: [
      { code: 'D6010', name: 'Surgical Placement of Implant Body - Endosteal', fee: 1950.00 },
    ],
    tab: 'unsent',
  },
  {
    id: '6',
    patientName: 'Abdul Abayad',
    patientCode: '(#0028)',
    patientDob: '09/30/1969',
    claimNumber: '#27082',
    claimType: 'E-claim Primary',
    createdDate: '04/24/2026',
    carrier: 'Delta Dental Ins.',
    status: 'readyForSubmission',
    notes: 'No pre-auth required',
    description: 'Waiting for the crown to be seated.',
    procedures: [
      { code: 'D2740', name: 'Crown - Porcelain/Ceramic Substrate', fee: 1200.00 },
    ],
    tab: 'unsent',
  },
  {
    id: '7',
    patientName: 'Keerthi Motupalli',
    patientCode: '(#0733)',
    patientDob: '11/12/1984',
    claimNumber: '#24007',
    claimType: 'E-claim Primary',
    createdDate: '04/16/2026',
    carrier: 'United Healthcare',
    status: 'readyForSubmission',
    notes: 'Deductible met',
    description: 'Paid Amount$169.00 Patient res...',
    procedures: [
      { code: 'D0150', name: 'Comprehensive Oral Evaluation - New Patient', fee: 110.00 },
      { code: 'D0210', name: 'Intraoral - Complete Series of Radiographic Images', fee: 165.00 },
    ],
    tab: 'unsent',
  },
  {
    id: '8',
    patientName: 'Jenny Dondeti',
    patientCode: '(#0055)',
    patientDob: '04/05/1979',
    claimNumber: '#28458',
    claimType: 'E-claim Primary',
    createdDate: '01/08/2026',
    carrier: 'Humana Dental',
    status: 'readyForSubmission',
    notes: 'Inactive subscriber policy reported',
    description: 'Member is not active on DOS Eff...',
    procedures: [
      { code: 'D3330', name: 'Endodontic Therapy - Molar Tooth', fee: 980.00 },
    ],
    tab: 'unsent',
  },
  {
    id: '9',
    patientName: 'Samuel Green',
    patientCode: '(#0119)',
    patientDob: '07/22/1962',
    claimNumber: '#27488',
    claimType: 'E-claim Primary',
    createdDate: '07/23/2025',
    carrier: 'Principal Financial',
    status: 'readyForSubmission',
    notes: 'Secondary insurance exists',
    description: 'It is a discounted plan',
    procedures: [
      { code: 'D2950', name: 'Core Buildup, Including Any Pins when Required', fee: 245.00 },
    ],
    tab: 'unsent',
  },

  // 10-15: ERRORED CLAIMS
  {
    id: '10',
    patientName: 'Keerthi Motupalli',
    patientCode: '(#788)',
    patientDob: '11/12/1984',
    claimNumber: '#24447',
    claimType: 'E-claim Primary',
    createdDate: '04/17/2026',
    sentDate: '04/17/2026',
    carrier: 'Blue Cross Blue Shield of Texas',
    status: 'readyForSubmission',
    clearingHouseMessage: '',
    notes: 'Prior submission failed due to network timeout.',
    description: 'Paid Amount$169.00 Patient res...',
    procedures: [
      { code: 'D0150', name: 'Comprehensive Oral Evaluation', fee: 110.00 },
    ],
    tab: 'errored',
    redAttachment: true,
  },
  {
    id: '11',
    patientName: 'Babar Magsi',
    patientCode: '(#85)',
    patientDob: '03/09/1987',
    claimNumber: '#25372',
    claimType: 'E-claim Primary',
    createdDate: '05/13/2026',
    sentDate: '05/13/2026',
    carrier: 'Metlife',
    status: 'error',
    clearingHouseMessage: 'Status Response (A3): Returned validation errors on claim subscriber info',
    notes: 'Subscriber ID format does not match Metlife requirements.',
    description: 'Onlay Preps #18, 19, 30 Prep Date: 01/08/2026 Seat Date: 01/29/2026 Dx: Babar Magsi sease with erosion into dentin...',
    procedures: [
      { code: 'D2643', name: 'Onlay - Porcelain/Ceramic - Three Surfaces', fee: 940.00 },
      { code: 'D2644', name: 'Onlay - Porcelain/Ceramic - Four+ Surfaces', fee: 1050.00 },
    ],
    tab: 'errored',
    redAttachment: false,
  },
  {
    id: '12',
    patientName: 'Bekhzod Ivanov',
    patientCode: '(#1059)',
    patientDob: '05/20/2001',
    claimNumber: '#22699',
    claimType: 'E-claim Primary',
    createdDate: '03/18/2026',
    sentDate: '03/18/2026',
    carrier: 'Cigna Dental',
    status: 'eobUploaded',
    clearingHouseMessage: '',
    notes: 'EOB received digitally, manual review pending.',
    description: 'F/U 06/15/2026*Banding date:1... (KS6 bur); dentin sealed with RelyX (light cured) Temporaries fabricated using Clinicians Choice matrix + Kettenbach Visalys Temps seated, adjusted, polished; occlusion checked Cemented with TempBond Clear; excess removed; contacts flossed and verified Shade: A3 (Vita) Final material: Lithium disilicate (Emax) Lab: Reliable Dental Lab POIG given Dr. LP',
    procedures: [
      { code: 'D8080', name: 'Comprehensive Orthodontic Treatment - Adolescent', fee: 3200.00 },
    ],
    tab: 'errored',
    redAttachment: true,
  },
  {
    id: '13',
    patientName: 'Thomas Gellar',
    patientCode: '(#1246)',
    patientDob: '08/08/1978',
    claimNumber: '#25011',
    claimType: 'E-claim Primary',
    createdDate: '05/19/2026',
    sentDate: '05/19/2026',
    carrier: 'CIGNA',
    status: 'eobUploaded',
    clearingHouseMessage: '',
    notes: 'Full implants chart sent as supporting narrative.',
    description: 'F/U 05/21/2026 BH."Claim Statu... CC "I was reffered by Dr. Anver and would like to have my implant #14 restored" Patient was reffered by Dr. Anver for restoration of implant #14: Implant info: #14 Straumann BLC WB 4.5 x 8mm Heal Abutment: RB/WB 5GH 3.5 AH 2 Remov healing abutment with a Straumann driv Placed scan body provided by Dr. Anver. Intraoral scan taken. Removed scan body and placed back healing abutment. NV: Deliver implant crown #14 (1hr) Franco RDA',
    procedures: [
      { code: 'D6058', name: 'Abutment Supported Porcelain Crown', fee: 1450.00 },
    ],
    tab: 'errored',
    redAttachment: true,
  },
  {
    id: '14',
    patientName: 'Ivan Todorov',
    patientCode: '(#63)',
    patientDob: '12/25/1992',
    claimNumber: '#25262',
    claimType: 'E-claim Primary',
    createdDate: '05/15/2026',
    sentDate: '05/15/2026',
    carrier: 'United Healthcare Dental',
    status: 'error',
    clearingHouseMessage: 'Status Response (A3): Returned claim rejected by payer - invalid tooth number',
    notes: 'Tooth #14 is invalid for the specified procedure code.',
    description: 'F/U 06/01/2026 BH. We have req...',
    procedures: [
      { code: 'D7140', name: 'Extraction, Erupted Tooth or Exposed Root', fee: 185.00 },
    ],
    tab: 'errored',
    redAttachment: false,
  },
  {
    id: '15',
    patientName: 'Carolyn Miller',
    patientCode: '(#112)',
    patientDob: '01/30/1985',
    claimNumber: '#24285',
    claimType: 'E-claim Primary',
    createdDate: '04/29/2026',
    sentDate: '04/29/2026',
    carrier: 'Cigna Dental',
    status: 'eobUploaded',
    clearingHouseMessage: 'Status Response (A3): Returned claim processed - payment pending',
    notes: 'Payment scheduled for release on next carrier cycle.',
    description: '"Paid Amount$199.80 Patient res..."',
    procedures: [
      { code: 'D2160', name: 'Amalgam - Three Surfaces, Primary or Permanent', fee: 175.00 },
    ],
    tab: 'errored',
    redAttachment: true,
  },

  // 18-30: HISTORY CLAIMS
  {
    id: '18',
    patientName: 'Gweneth Taylor',
    patientCode: '(#71)',
    patientDob: '06/06/1980',
    claimNumber: '#25461',
    claimType: 'E-claim Primary',
    createdDate: '05/22/2026',
    sentDate: '05/22/2026',
    printedDate: '—',
    carrier: 'CIGNA',
    status: 'inProcess',
    clearingHouseMessage: 'Status Response (A0): The claim has been received by the clearinghouse.',
    notes: 'Sent digitally via Medflow portal.',
    description: 'Crown Prep 05/20/2026 06/16/2026',
    procedures: [{ code: 'D2740', name: 'Crown - Porcelain/Ceramic', fee: 1150.00 }],
    tab: 'history',
    redAttachment: false,
  },
  {
    id: '19',
    patientName: 'William Helm',
    patientCode: '(#93)',
    patientDob: '04/18/1971',
    claimNumber: '#25458',
    claimType: 'E-claim Primary',
    createdDate: '05/22/2026',
    sentDate: '05/22/2026',
    printedDate: '—',
    carrier: 'Anthem',
    status: 'inProcess',
    clearingHouseMessage: 'Status Response (A0): The claim has been received by the clearinghouse.',
    notes: 'Requires clinical chart review.',
    description: 'Babar Magsi',
    procedures: [{ code: 'D1110', name: 'Prophylaxis - Adult', fee: 95.00 }],
    tab: 'history',
    redAttachment: false,
  },
  {
    id: '20',
    patientName: 'Gweneth Taylor',
    patientCode: '(#71)',
    patientDob: '06/06/1980',
    claimNumber: '#25443',
    claimType: 'E-claim Primary',
    createdDate: '05/22/2026',
    sentDate: '05/22/2026',
    printedDate: '—',
    carrier: 'MetLife',
    status: 'inProcess',
    clearingHouseMessage: 'Status Response (A0): The claim has been received by the clearinghouse.',
    notes: 'Digital x-rays attached.',
    description: '',
    procedures: [{ code: 'D4341', name: 'Periodontal Scaling & Root Planing', fee: 280.00 }],
    tab: 'history',
    redAttachment: true,
  },
  {
    id: '21',
    patientName: 'Audrey Hepburn',
    patientCode: '(#71)',
    patientDob: '05/04/1929',
    claimNumber: '#25439',
    claimType: 'E-claim Primary',
    createdDate: '05/22/2026',
    sentDate: '05/22/2026',
    printedDate: '—',
    carrier: 'CIGNA',
    status: 'inProcess',
    clearingHouseMessage: 'Status Response (A0): The claim has been received by the clearinghouse.',
    notes: '',
    description: '',
    procedures: [{ code: 'D0120', name: 'Periodic Oral Evaluation', fee: 55.00 }],
    tab: 'history',
    redAttachment: false,
  },
  {
    id: '22',
    patientName: 'Marilyn Monroe',
    patientCode: '(#582)',
    patientDob: '06/01/1926',
    claimNumber: '#25435',
    claimType: 'E-claim Primary',
    createdDate: '05/22/2026',
    sentDate: '05/22/2026',
    printedDate: '—',
    carrier: 'CIGNA',
    status: 'accepted',
    clearingHouseMessage: 'Status Response (A2): Acknowledged/Accept at payer level.',
    notes: '',
    description: '',
    procedures: [{ code: 'D2331', name: 'Resin-Based Composite - 2 Surfaces', fee: 210.00 }],
    tab: 'history',
    redAttachment: false,
  },
  {
    id: '23',
    patientName: 'Elvis Presley',
    patientCode: '(#1044)',
    patientDob: '01/08/1935',
    claimNumber: '#25415',
    claimType: 'E-claim Primary',
    createdDate: '05/21/2026',
    sentDate: '05/21/2026',
    printedDate: '—',
    carrier: 'MetLife',
    status: 'inProcess',
    clearingHouseMessage: 'Status Response (A0): The claim has been received by the clearinghouse.',
    notes: '',
    description: '',
    procedures: [{ code: 'D2740', name: 'Crown - Porcelain/Ceramic Substrate', fee: 1200.00 }],
    tab: 'history',
    redAttachment: false,
  },
  {
    id: '24',
    patientName: 'John Lennon',
    patientCode: '(#227)',
    patientDob: '10/09/1940',
    claimNumber: '#25403',
    claimType: 'E-claim Primary',
    createdDate: '05/21/2026',
    sentDate: '05/21/2026',
    printedDate: '—',
    carrier: 'Aetna Dental Plans',
    status: 'accepted',
    clearingHouseMessage: 'Status Response (A2): Acknowledged/Accept at payer level.',
    notes: '',
    description: '',
    procedures: [{ code: 'D1110', name: 'Prophylaxis - Adult', fee: 95.00 }],
    tab: 'history',
    redAttachment: false,
  },
  {
    id: '25',
    patientName: 'Paul McCartney',
    patientCode: '(#24)',
    patientDob: '06/18/1942',
    claimNumber: '#25397',
    claimType: 'E-claim Primary',
    createdDate: '05/22/2026',
    sentDate: '05/22/2026',
    printedDate: '—',
    carrier: 'CIGNA',
    status: 'accepted',
    clearingHouseMessage: 'Status Response (A2): Acknowledged/Accept at payer level.',
    notes: '',
    description: '',
    procedures: [{ code: 'D2950', name: 'Core Buildup, Including Any Pins', fee: 245.00 }],
    tab: 'history',
    redAttachment: false,
  },
  {
    id: '26',
    patientName: 'George Harrison',
    patientCode: '(#19)',
    patientDob: '02/25/1943',
    claimNumber: '#25313',
    claimType: 'E-claim Primary',
    createdDate: '05/19/2026',
    sentDate: '05/19/2026',
    printedDate: '—',
    carrier: 'CIGNA',
    status: 'accepted',
    clearingHouseMessage: 'Status Response (A2): Acknowledged/Accept at payer level.',
    notes: '',
    description: '',
    procedures: [{ code: 'D0150', name: 'Comprehensive Oral Evaluation', fee: 110.00 }],
    tab: 'history',
    redAttachment: false,
  },
  {
    id: '27',
    patientName: 'Ringo Starr',
    patientCode: '(#200)',
    patientDob: '07/07/1940',
    claimNumber: '#25309',
    claimType: 'E-claim Primary',
    createdDate: '05/19/2026',
    sentDate: '05/19/2026',
    printedDate: '—',
    carrier: 'CIGNA',
    status: 'accepted',
    clearingHouseMessage: 'Status Response (A2): Acknowledged/Accept at payer level.',
    notes: '',
    description: '',
    procedures: [{ code: 'D3330', name: 'Endodontic Therapy - Molar', fee: 980.00 }],
    tab: 'history',
    redAttachment: false,
  },
  {
    id: '28',
    patientName: 'Bob Dylan',
    patientCode: '(#1260)',
    patientDob: '05/24/1941',
    claimNumber: '#25303',
    claimType: 'E-claim Primary',
    createdDate: '05/18/2026',
    sentDate: '05/18/2026',
    printedDate: '—',
    carrier: 'Aetna Dental Plans',
    status: 'accepted',
    clearingHouseMessage: 'Status Response (A2): Acknowledged/Accept at payer level.',
    notes: '',
    description: 'Crown Prep 05/14/2026 06/04/2026',
    procedures: [{ code: 'D2740', name: 'Crown - Porcelain/Ceramic', fee: 1150.00 }],
    tab: 'history',
    redAttachment: false,
  },
  {
    id: '29',
    patientName: 'Jimi Hendrix',
    patientCode: '(#308)',
    patientDob: '11/27/1942',
    claimNumber: '#25300',
    claimType: 'E-claim Primary',
    createdDate: '05/18/2026',
    sentDate: '05/18/2026',
    printedDate: '—',
    carrier: 'MetLife',
    status: 'inProcess',
    clearingHouseMessage: 'Status Response (A0): The claim has been received by the clearinghouse.',
    notes: '',
    description: '',
    procedures: [{ code: 'D4910', name: 'Periodontal Maintenance', fee: 140.00 }],
    tab: 'history',
    redAttachment: false,
  },
  {
    id: '30',
    patientName: 'Eric Clapton',
    patientCode: '(#99)',
    patientDob: '03/30/1945',
    claimNumber: '#25287',
    claimType: 'E-claim Primary',
    createdDate: '05/18/2026',
    sentDate: '05/18/2026',
    printedDate: '—',
    carrier: 'MetLife',
    status: 'acceptedPaid',
    clearingHouseMessage: 'Status Response (A0): The claim has been received by the clearinghouse.',
    notes: '',
    description: 'Babar Magsi',
    procedures: [{ code: 'D6010', name: 'Surgical Placement of Implant Body', fee: 1950.00 }],
    tab: 'history',
    redAttachment: false,
  },

  // 31-32: OUTSTANDING CLAIMS
  {
    id: '31',
    patientName: 'Zachary Taylor',
    patientCode: '(#1124)',
    patientDob: '07/17/1984',
    claimNumber: '#25258',
    claimType: 'E-claim Primary',
    createdDate: '05/13/2026',
    sentDate: '05/15/2026',
    printedDate: '—',
    subscriber: 'Sean Carpenter',
    carrier: 'Aetna Dental Plans',
    planName: 'Aetna PPO (083321)',
    status: 'accepted',
    clearingHouseMessage: 'Status Response (A2): Acknowledged/Accept at payer level.',
    submittedValue: 318.00,
    notes: 'Prior authorization confirmed',
    description: '',
    procedures: [
      { code: 'D0120', name: 'Periodic Oral Evaluation', fee: 55.00 },
      { code: 'D0210', name: 'Intraoral - Complete Series', fee: 263.00 },
    ],
    tab: 'outstanding',
    redAttachment: false,
  },
  {
    id: '32',
    patientName: 'Amy Guy',
    patientCode: '(#942)',
    patientDob: '11/04/1991',
    claimNumber: '#24994',
    claimType: 'E-claim Primary',
    createdDate: '05/02/2026',
    sentDate: '05/04/2026',
    printedDate: '—',
    subscriber: 'Amy Guy',
    carrier: 'Blue Cross',
    planName: 'BCBS Choice (120984)',
    status: 'inProcess',
    clearingHouseMessage: 'Status Response (A0): The claim has been received by the clearinghouse.',
    submittedValue: 5900.00,
    notes: 'Sent digitally.',
    description: 'F/U 06/01/2026 BH.',
    procedures: [
      { code: 'D6010', name: 'Implant Placement', fee: 5900.00 },
    ],
    tab: 'outstanding',
    redAttachment: false,
  },

  // 33-40: PREDETERMINATION CLAIMS
  {
    id: '33',
    patientName: 'Leticia Carter',
    patientCode: '(#253)',
    patientDob: '08/12/1988',
    claimNumber: '#24310',
    claimType: 'E-claim Primary',
    sentDate: '04/06/2026',
    carrier: 'CIGNA',
    treatingProvider: 'Sabour S.',
    status: 'accepted',
    clearingHouseMessage: 'Status Response (A2): Acknowledged/Accept at payer level.',
    notes: 'Pre-auth crown replacement.',
    description: '',
    procedures: [{ code: 'D2750', name: 'Crown - Porcelain Fused to High Noble Metal', fee: 1100.00 }],
    tab: 'predetermination',
    attachmentColor: 'green',
  },
  {
    id: '34',
    patientName: 'Russell Rudolf',
    patientCode: '(#752)',
    patientDob: '10/24/1975',
    claimNumber: '#23814',
    claimType: 'Manual Primary',
    sentDate: '—',
    carrier: 'MetLife',
    treatingProvider: 'Sabour S.',
    status: 'manualClaim',
    clearingHouseMessage: '',
    notes: 'Paper pre-determination.',
    description: 'Babar Magsi',
    procedures: [{ code: 'D4341', name: 'Periodontal Scaling & Root Planing', fee: 280.00 }],
    tab: 'predetermination',
    attachmentColor: 'blue',
    showEye: true,
  },
  {
    id: '35',
    patientName: 'Evan Romero',
    patientCode: '(#812)',
    patientDob: '05/16/1990',
    claimNumber: '#23813',
    claimType: 'E-claim Primary',
    sentDate: '03/12/2026',
    carrier: 'MetLife',
    treatingProvider: 'Sabour S.',
    status: 'inProcess',
    clearingHouseMessage: 'Status Response (A0): The claim has been received by the clearinghouse.',
    notes: 'X-rays attached.',
    description: '',
    procedures: [{ code: 'D2331', name: 'Resin Composite - 2 Surfaces', fee: 210.00 }],
    tab: 'predetermination',
    attachmentColor: 'red',
  },
  {
    id: '36',
    patientName: 'Gabriel Medina',
    patientCode: '(#226)',
    patientDob: '12/03/1995',
    claimNumber: '#23709',
    claimType: 'E-claim Primary',
    sentDate: '03/06/2026',
    carrier: 'Delta Dental',
    treatingProvider: 'Sabour S.',
    status: 'inProcess',
    clearingHouseMessage: 'Status Response (A1): The claim is in process at the payer.',
    notes: 'General cleaning auth.',
    description: '',
    procedures: [{ code: 'D1110', name: 'Prophylaxis - Adult', fee: 95.00 }],
    tab: 'predetermination',
    attachmentColor: 'red',
  },
  {
    id: '37',
    patientName: 'Carolyn Miller',
    patientCode: '(#444)',
    patientDob: '01/30/1985',
    claimNumber: '#15152',
    claimType: 'E-claim Primary',
    sentDate: '11/06/2024',
    carrier: 'Delta Dental of California Federal Government plan',
    treatingProvider: 'Sabour S.',
    status: 'acceptedForProcessing',
    clearingHouseMessage: 'Accepted For Processing',
    notes: 'Bridges auth.',
    description: 'Dental bridges replace missing teeth tooth 20 is broken',
    procedures: [{ code: 'D6240', name: 'Pontic - Porcelain Fused to Noble Metal', fee: 950.00 }],
    tab: 'predetermination',
    attachmentColor: 'blue',
  },
  {
    id: '38',
    patientName: 'Babar Magsi',
    patientCode: '(#776)',
    patientDob: '03/09/1987',
    claimNumber: '#15117',
    claimType: 'Manual Primary',
    sentDate: '—',
    carrier: 'MetLife',
    treatingProvider: 'Sabour S.',
    status: 'manualClaim',
    clearingHouseMessage: '',
    notes: 'Manual submission.',
    description: '',
    procedures: [{ code: 'D6010', name: 'Surgical Placement of Implant Body', fee: 1950.00 }],
    tab: 'predetermination',
    attachmentColor: 'blue',
  },
  {
    id: '39',
    patientName: 'Ivan Todorov',
    patientCode: '(#585)',
    patientDob: '12/25/1992',
    claimNumber: '#14313',
    claimType: 'E-claim Primary',
    sentDate: '09/13/2024',
    carrier: 'GEHA Connection',
    treatingProvider: 'Sabour S.',
    status: 'inProcess',
    clearingHouseMessage: 'Status Response (A1): The claim is in process at the payer.',
    notes: 'Extraction pre-auth.',
    description: '',
    procedures: [{ code: 'D7140', name: 'Extraction, Erupted Tooth', fee: 185.00 }],
    tab: 'predetermination',
    attachmentColor: 'green',
  },
  {
    id: '40',
    patientName: 'Zachary Taylor',
    patientCode: '(#998)',
    patientDob: '07/17/1984',
    claimNumber: '#14218',
    claimType: 'E-claim Primary',
    sentDate: '09/09/2024',
    carrier: 'Aetna Dental Plans',
    treatingProvider: 'Sabour S.',
    status: 'accepted',
    clearingHouseMessage: 'Status Response (A2): Acknowledged/Accept at payer level.',
    notes: 'Complete x-rays pre-auth.',
    description: '',
    procedures: [{ code: 'D0210', name: 'Intraoral - Complete Series', fee: 263.00 }],
    tab: 'predetermination',
    attachmentColor: 'green',
  },
];

// High Fidelity Mock Dentical Reports Data
export const DENTICAL_REPORTS_MOCK = [
  {
    id: 'dr_1',
    fileName: 'dentical_remittance_advice_052026.pdf',
    reportDate: '05/20/2026',
    dateCreated: '05/21/2026',
  },
  {
    id: 'dr_2',
    fileName: 'dentical_eligibility_status_051826.pdf',
    reportDate: '05/18/2026',
    dateCreated: '05/18/2026',
  },
  {
    id: 'dr_3',
    fileName: 'dentical_treatment_authorization_request_051526.pdf',
    reportDate: '05/15/2026',
    dateCreated: '05/16/2026',
  },
  {
    id: 'dr_4',
    fileName: 'dentical_claims_payment_summary_051026.pdf',
    reportDate: '05/10/2026',
    dateCreated: '05/11/2026',
  },
];

// High Fidelity Mock ERA (Electronic Remittance Advice) Reports Data
export const INITIAL_ERA_REPORTS = [
  // ACTIVE CLAIMS (eraTab = 'active')
  {
    id: 'era_1',
    patientId: 'PT-0418',
    patientName: 'Leticia Carter',
    claimNumber: '#25390',
    carrier: 'Blue Cross Blue Shield of Texas',
    status: 'Paid',
    amountSubmitted: 1205.00,
    amountPaid: 964.00,
    patientResponsibility: 241.00,
    writeOff: 0.00,
    dateReceived: '05/22/2026',
    paymentType: 'EFT',
    eraTab: 'active',
  },
  {
    id: 'era_2',
    patientId: 'PT-0097',
    patientName: 'Russell Rudolf',
    claimNumber: '#25401',
    carrier: 'Metlife',
    status: 'Paid',
    amountSubmitted: 420.00,
    amountPaid: 336.00,
    patientResponsibility: 0.00,
    writeOff: 84.00,
    dateReceived: '05/21/2026',
    paymentType: 'Check',
    eraTab: 'active',
  },
  {
    id: 'era_3',
    patientId: 'PT-0134',
    patientName: 'Evan Romero',
    claimNumber: '#25407',
    carrier: 'Aetna Dental',
    status: 'Denial',
    amountSubmitted: 210.00,
    amountPaid: 0.00,
    patientResponsibility: 210.00,
    writeOff: 0.00,
    dateReceived: '05/20/2026',
    paymentType: 'EFT',
    eraTab: 'active',
  },
  {
    id: 'era_4',
    patientId: 'PT-0011',
    patientName: 'Gabriel Medina',
    claimNumber: '#25474',
    carrier: 'Guardian Life',
    status: 'Paid',
    amountSubmitted: 130.00,
    amountPaid: 104.00,
    patientResponsibility: 26.00,
    writeOff: 0.00,
    dateReceived: '05/19/2026',
    paymentType: 'EFT',
    eraTab: 'active',
  },
  {
    id: 'era_5',
    patientId: 'PT-0085',
    patientName: 'Babar Magsi',
    claimNumber: '#25372',
    carrier: 'Metlife',
    status: 'Paid',
    amountSubmitted: 1990.00,
    amountPaid: 1492.50,
    patientResponsibility: 100.00,
    writeOff: 397.50,
    dateReceived: '05/18/2026',
    paymentType: 'Check',
    eraTab: 'active',
  },
  {
    id: 'era_6',
    patientId: 'PT-0112',
    patientName: 'Carolyn Miller',
    claimNumber: '#24285',
    carrier: 'Cigna Dental',
    status: 'Paid',
    amountSubmitted: 175.00,
    amountPaid: 140.00,
    patientResponsibility: 35.00,
    writeOff: 0.00,
    dateReceived: '05/17/2026',
    paymentType: 'EFT',
    eraTab: 'active',
  },

  // VOIDED CLAIMS (eraTab = 'voided')
  {
    id: 'era_7',
    patientId: 'PT-0063',
    patientName: 'Ivan Todorov',
    claimNumber: '#25262',
    carrier: 'United Healthcare Dental',
    status: 'Voided',
    amountSubmitted: 185.00,
    amountPaid: 0.00,
    patientResponsibility: 0.00,
    writeOff: 0.00,
    dateReceived: '05/15/2026',
    paymentType: '—',
    eraTab: 'voided',
  },
  {
    id: 'era_8',
    patientId: 'PT-1246',
    patientName: 'Thomas Gellar',
    claimNumber: '#25011',
    carrier: 'CIGNA',
    status: 'Voided',
    amountSubmitted: 1450.00,
    amountPaid: 0.00,
    patientResponsibility: 0.00,
    writeOff: 0.00,
    dateReceived: '05/14/2026',
    paymentType: '—',
    eraTab: 'voided',
  },
];

export const REJECTED_MOCK_DATA = [
  {
    id: '16',
    patientName: 'Hassan Al-Saeed',
    patientCode: '(#554)',
    patientDob: '02/12/1980',
    claimNumber: '#21182',
    claimType: 'E-claim Primary',
    createdDate: '04/10/2026',
    sentDate: '04/10/2026',
    printedDate: '—',
    carrier: 'Delta Dental Ins.',
    status: 'rejected',
    eraStatus: 'Rejected by Payer',
    clearingHouseMessage: 'Reject Reason: Patient eligibility not found on date of service.',
    notes: 'Checked insurance card, subscriber ID matches but coverage terminated.',
    description: 'F/U 05/10/2026. Verification failed.',
    procedures: [{ code: 'D0120', name: 'Periodic Oral Evaluation', fee: 55.00 }],
    tab: 'rejected',
    redAttachment: false,
  },
  {
    id: '17',
    patientName: 'Emily Rose',
    patientCode: '(#302)',
    patientDob: '05/06/1994',
    claimNumber: '#23190',
    claimType: 'E-claim Primary',
    createdDate: '03/05/2026',
    sentDate: '03/05/2026',
    printedDate: '03/06/2026',
    carrier: 'Aetna Dental',
    status: 'rejected',
    eraStatus: 'Rejected by Clearinghouse',
    clearingHouseMessage: 'Reject Reason: Missing signature indicator code.',
    notes: 'Dentist signature block was empty. Re-added and prepared.',
    description: 'Need doctor signature on file.',
    procedures: [{ code: 'D2740', name: 'Crown - Porcelain/Ceramic', fee: 1150.00 }],
    tab: 'rejected',
    redAttachment: true,
  },
];

export const TABS = [
  'UNSENT CLAIMS',
  'ERRORED',
  'REJECTED',
  'HISTORY',
  'OUTSTANDING CLAIMS',
  'PREDETERMINATION',
  'DENTICAL REPORTS',
  'ERA REPORTS',
];
export const SORT_REPORT_OPTIONS = [ { value: 'none', label: 'None' }, { value: 'sentDate', label: 'Sent on Date' }, { value: 'printedDate', label: 'Printed on Date' }, { value: 'patientName', label: 'Patient Name' }, { value: 'carrierName', label: 'Carrier Name' }, { value: 'dos', label: 'Date of Service' }, { value: 'claimDate', label: 'Claim Date' } ];
export const FILTER_DATE_OPTIONS = [ { value: 'all', label: 'All dates' }, { value: 'range', label: 'Range' }, { value: 'thisWeek', label: 'This Week' }, { value: 'thisMonth', label: 'This Month' }, { value: 'last7Days', label: 'Last 7 days' }, { value: 'lastWeek', label: 'Last Week' }, { value: 'last4Weeks', label: 'Last 4 Weeks' }, { value: 'lastMonth', label: 'Last Month' }, { value: 'last3Months', label: 'Last 3 Months' }, { value: 'last12Months', label: 'Last 12 Months' }, { value: 'monthToDate', label: 'Month to date' }, { value: 'quarterToDate', label: 'Quarter to date' }, { value: 'yearToDate', label: 'Year to date' }, { value: 'lastYear', label: 'Last Year' } ];
